### ISSUE TITLE
API break with the latest semanticscholar package v0.3.2

### ISSUE THREAD

**Issue by dylangageot** [oowekyala/citegraph#2]
Hey oowekyala, hope you are doing well!

I have wanted to reuse your tool lately but I ran into an exception while trying to use it.
I have installed all the dependencies to their latest released versions. 
It looks like semanticscholar got its API changed... here is the traceback:

> Traceback (most recent call last):
>   File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
>     return _run_code(code, main_globals, None,
>   File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
>     exec(code, run_globals)
>   File "/home/gageotd/Documents/workspace/citegraph/src/citegraph/__main__.py", line 142, in <module>
>     main(args, parser.error)
>   File "/home/gageotd/Documents/workspace/citegraph/src/citegraph/__main__.py", line 118, in main
>     with PaperDb(bibdata=bibdata, dbfile=db_loc) as db:
>   File "/home/gageotd/Documents/workspace/citegraph/src/citegraph/semapi.py", line 230, in __exit__
>     raise exc_val
>   File "/home/gageotd/Documents/workspace/citegraph/src/citegraph/__main__.py", line 120, in main
>     graph = create_graph(seeds=seeds, biblio=bibdata, params=params, db=db)
>   File "/home/gageotd/Documents/workspace/citegraph/src/citegraph/explore.py", line 249, in smart_fetch
>     roots = [resp for id in seeds for resp in [db.fetch_from_id(id)] if resp or not handle_api_failure(id, None)]
>   File "/home/gageotd/Documents/workspace/citegraph/src/citegraph/explore.py", line 249, in <listcomp>
>     roots = [resp for id in seeds for resp in [db.fetch_from_id(id)] if resp or not handle_api_failure(id, None)]
>   File "/home/gageotd/Documents/workspace/citegraph/src/citegraph/semapi.py", line 163, in fetch_from_id
>     paper_dict: Dict = semanticscholar.paper(paper_id)
> AttributeError: module 'semanticscholar' has no attribute 'paper'. Did you mean: 'Paper'?

I "fixed" it by setting semanticscholar version to 0.2.1 in `DEPENDENCIES`, which might be a good workaround for the moment.

Dylan

**Comment by oowekyala** [comment]
Hi Dylan, thanks for reporting! I hope you're doing well too!

This unfortunately got buried in my notifications, but I have now updated semanticscholar to v0.4.1 and fixed the api incompatibilities. I hope your workaround helped you get something out of this program anyway 

Cheers
Clément
